remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Medical Instrument Classifier
description: An image classification application that classifies 10 different types of medical instruments.

author:
  name: Shahidul Islam